
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsSoap", targetNamespace = "http://org.tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsSoap {


    /**
     * 
     * @param requestData
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "XmsRequest", action = "http://org.tempuri.org/XmsRequest")
    @WebResult(name = "XmsRequestResult", targetNamespace = "http://org.tempuri.org/")
    @RequestWrapper(localName = "XmsRequest", targetNamespace = "http://org.tempuri.org/", className = "org.org.tempuri.XmsRequest")
    @ResponseWrapper(localName = "XmsRequestResponse", targetNamespace = "http://org.tempuri.org/", className = "org.org.tempuri.XmsRequestResponse")
    public Object xmsRequest(
            @WebParam(name = "requestData", targetNamespace = "http://org.tempuri.org/")
                    String requestData);

}
